#!/bin/sh

#
# Copyright (C) 2018 Intel Corporation
#
# SPDX-License-Identifier: BSD-3-Clause
#

# Path to the script location, e.g. /home/hcloud/iosm/imc_start.sh
SCRIPT=$(readlink -f "$0")
# Directory name this script is in, thus /home/hcloud/iosm/
SCRIPT_DIR=$(dirname "$SCRIPT")

while getopts h option
do
  case "${option}"
  in
    h) echo "usage: $0 <modem_instance_nr: 0..3>"
       exit 0;;
  esac
done

if [ "$#" -eq 0 ]; then
  MODEM_ID=0
  RPC0_DEV="/dev/rpc"
  RPC1_DEV="/dev/rpc1"
elif [ $1 -ge 0 ] && [ $1 -lt 4 ]; then
  MODEM_ID=$1
  RPC0_DEV="/dev/rpc0_$MODEM_ID"
  RPC1_DEV="/dev/rpc1_$MODEM_ID"
else
  echo "usage: $0 <modem_instance_nr: 0..3>"
  exit 1
fi

# configure RPC channels
$SCRIPT_DIR/wwan_cfg -r wwan$MODEM_ID -n wwan$MODEM_ID.rpc0_$MODEM_ID -v 257 -c $RPC0_DEV -m 32768 -i $MODEM_ID

# Exit if wwan_cfg fails
rc=$?; if [ $rc != 0 ]; then exit $rc; fi

# If Modem supports 2 RPC channels then uncomment the below line.
#$SCRIPT_DIR/wwan_cfg -r wwan$MODEM_ID -n wwan$MODEM_ID.rpc1_$MODEM_ID -v 262 -c $RPC1_DEV -m 32768 -i $MODEM_ID
