#!/bin/sh

#
# Copyright (C) 2018 Intel Corporation
#
# SPDX-License-Identifier: (BSD-3-Clause)
#

delete_interface()
{
  IF_NAME=$1

  ip link del "$IF_NAME"
}


delete_all_interfaces()
{
  VLAN_ID=9
  IF_ID=0

  while [ "$VLAN_ID" -le 41 ]
  do
    delete_interface "$OGRS$IF_ID"
    VLAN_ID=$((VLAN_ID+1))
    IF_ID=$((IF_ID+1))
  done
}

# Path to the script location, e.g. /home/hcloud/iosm/imc_start.sh
SCRIPT=$(readlink -f "$0")
# Directory name this script is in, thus /home/hcloud/iosm/
SCRIPT_DIR=$(dirname "$SCRIPT")

MODEM_ID=0
OGRS="ogrs"
while getopts ":i:ah:" option
do
  case ${option}
  in
    i) VLAN_ID="${OPTARG}"
       VLAN_ID=$((VLAN_ID+9))
       delete_interface "$OGRS${OPTARG}"
       ;;

    a) delete_all_interfaces
       exit 0
       ;;

    : ) echo "usage: $0 [-i <interface number>] [-a for all interfaces] [-h for help]"
       exit 0
       ;;
  esac
done



