#!/bin/sh

#
# Copyright (C) 2018 Intel Corporation
#
# SPDX-License-Identifier: BSD-3-Clause
#

# Path to the script location, e.g. /home/hcloud/iosm/imc_start.sh
SCRIPT=$(readlink -f "$0")
# Directory name this script is in, thus /home/hcloud/iosm/
SCRIPT_DIR=$(dirname "$SCRIPT")

while getopts h option
do
  case "${option}"
  in
    h) echo "usage: $0 <modem_instance_nr: 0..3>"
       exit 0;;
  esac
done

if [ "$#" -eq 0 ]; then
  MODEM_ID=0
  INMLL0="inmll0"
  INMLL1="inmll1"
elif [ $1 -ge 0 ] && [ $1 -lt 4 ]; then
  MODEM_ID=$1
  INMLL0="inmll0_$MODEM_ID"
  INMLL1="inmll1_$MODEM_ID"
else
  echo "usage: $0 <modem_instance_nr: 0..3>"
  exit 1
fi

VLAN_ID_0=513
VLAN_ID_1=514

SUBNET_0=241
SUBNET_1=242

$SCRIPT_DIR/wwan_cfg -r wwan$MODEM_ID -n $INMLL0 -v $VLAN_ID_0 -i $MODEM_ID

# Exit if wwan_cfg fails
rc=$?; if [ $rc != 0 ]; then exit $rc; fi

ifconfig $INMLL0 down

# configure interface inmll0
ifconfig $INMLL0 192.168.$SUBNET_0.2
ifconfig $INMLL0 up
route add -net 192.168.$SUBNET_0.0 netmask 255.255.255.255 gw 192.168.$SUBNET_0.3 $INMLL0
ifconfig $INMLL0


$SCRIPT_DIR/wwan_cfg -r wwan$MODEM_ID -n $INMLL1 -v $VLAN_ID_1 -i $MODEM_ID

# Exit if wwan_cfg fails
rc=$?; if [ $rc != 0 ]; then exit $rc; fi

ifconfig $INMLL1 down

#configure interface inmll1
ifconfig $INMLL1 192.168.$SUBNET_1.2
route add -net 192.168.$SUBNET_1.0 netmask 255.255.255.255 gw 192.168.$SUBNET_1.3 $INMLL1
ifconfig $INMLL1

