#!/bin/sh

#
# Copyright (C) 2018 Intel Corporation
#
# SPDX-License-Identifier: (BSD-3-Clause)
#

create_interface()
{
  IF_NAME=$1

  ifconfig "$IF_NAME" down

  "$SCRIPT_DIR"/wwan_cfg -r wwan"$MODEM_ID" -n "$IF_NAME" -v "$VLAN_ID" -i "$MODEM_ID"
  # Exit if wwan_cfg fails
  rc=$?; if [ $rc != 0 ]; then exit $rc; fi

  SUBNET=$((MODEM_ID*10+VLAN_ID))


  # configure interface 0
  ifconfig "$IF_NAME" 192.168."$SUBNET".2
  ifconfig "$IF_NAME" up
  ifconfig "$IF_NAME" hw ether 00:49:4e:4d:30:00
  route add -net 192.168."$SUBNET".0 netmask 255.255.255.255 gw 192.168."$SUBNET".3 "$IF_NAME"
  ifconfig "$IF_NAME"
}


create_all_interfaces()
{
  VLAN_ID=9
  IF_ID=0

  while [ "$VLAN_ID" -le 41 ]
  do
    create_interface "$OGRS$IF_ID"
    VLAN_ID=$((VLAN_ID+1))
    IF_ID=$((IF_ID+1))
  done
}

# Path to the script location, e.g. /home/hcloud/iosm/imc_start.sh
SCRIPT=$(readlink -f "$0")
# Directory name this script is in, thus /home/hcloud/iosm/
SCRIPT_DIR=$(dirname "$SCRIPT")

MODEM_ID=0
OGRS="ogrs"
while getopts ":i:ah:" option
do
  case ${option}
  in
    i) VLAN_ID="${OPTARG}"
       VLAN_ID=$((VLAN_ID+9))
       create_interface "$OGRS${OPTARG}"
       ;;

    a) create_all_interfaces
       exit 0
       ;;

    : ) echo "usage: $0 [-i <interface number>] [-a for all interfaces] [-h for help]"
       exit 0
       ;;
  esac
done



