#!/bin/sh

#
# Copyright (C) 2018 Intel Corporation
#
# SPDX-License-Identifier: BSD-3-Clause
#

while getopts h option
do
  case "${option}"
  in
    h) echo "usage: $0 <modem_instance_nr: 0..3>"
       exit 0;;
  esac
done

if [ "$#" -eq 0 ]; then
  MODEM_ID=0
  IAT0_DEV="/dev/iat"
  IAT1_DEV="/dev/iat1"
elif [ $1 -ge 0 ] && [ $1 -lt 4 ]; then
  MODEM_ID=$1
  IAT0_DEV="/dev/iat0_$MODEM_ID"
  IAT1_DEV="/dev/iat1_$MODEM_ID"
else
  echo "usage: $0 <modem_instance_nr: 0..3>"
  exit 1
fi

# delete AT channels
ip link del wwan$MODEM_ID.iat0_$MODEM_ID
ip link del wwan$MODEM_ID.iat1_$MODEM_ID
