#!/bin/sh

#
# Copyright (C) 2018 Intel Corporation
#
# SPDX-License-Identifier: BSD-3-Clause
#

# Path to the script location, e.g. /home/hcloud/iosm/imc_start.sh
SCRIPT=$(readlink -f "$0")
# Directory name this script is in, thus /home/hcloud/iosm/
SCRIPT_DIR=$(dirname "$SCRIPT")

while getopts h option
do
  case "${option}"
  in
    h) echo "usage: $0 <modem_instance_nr: 0..3>"
       exit 0;;
  esac
done

if [ "$#" -eq 0 ]; then
  MODEM_ID=0
  TSYNC_DEV="/dev/tsync"
elif [ $1 -ge 0 ] && [ $1 -lt 4 ]; then
  MODEM_ID=$1
  TSYNC_DEV="/dev/tsync_$MODEM_ID"
else
  echo "usage: $0 <modem_instance_nr: 0..3>"
  exit 1
fi

# configure tsync channels
$SCRIPT_DIR/wwan_cfg -r wwan$MODEM_ID -n wwan$MODEM_ID.tsync$MODEM_ID -v 264 -c $TSYNC_DEV -m 32768 -i $MODEM_ID

